// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ZipperExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ZipperExtension.ff9d6561-11c0-4eaa-b5ee-9d602ad3167a";
        public const string Name = "Zipper Extension";
        public const string Description = @"Visual Studio extension to easily zip project files excluding the bin and obj directories.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "SigDev";
        public const string Tags = "";
    }
}
