// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ZipperExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ZipperExtension.ff9d6561-11c0-4eaa-b5ee-9d670ad3167a";
        public const string Name = "ZipperExtension";
        public const string Description = @"Visual Studio extension to easily zip project files excluding the bin and obj directoriesVisual Studio extension to ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "SigDev";
        public const string Tags = "";
    }
}
