// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ZipperExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ZipperExtensionString = "1d319b23-24c1-4e01-9c95-cd50eea3438b";
        public static Guid ZipperExtension = new Guid(ZipperExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int TopMenuGroup = 0x0002;
        public const int ZipProject = 0x0100;
        public const int ZipSettings = 0x0101;
    }
}